import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bot,
  CalendarDays,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleDot,
  Copy,
  Download,
  Eye,
  EyeOff,
  File,
  ClipboardCheck,
  ClipboardPaste,
  FileSpreadsheet,
  FileText,
  FileUp,
  Filter,
  Folder,
  GripVertical,
  Info,
  Keyboard,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  PieChart,
  MessageCircleQuestion,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  PiggyBank,
  Plus,
  Receipt,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  Sparkles,
  Split,
  Square,
  Sun,
  Tag,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TrendingDown,
  TrendingUp,
  Undo2,
  Upload,
  User,
  UserPlus,
  Users,
  UserSearch,
  UserX,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Material-Symbols name → Lucide component map. Add new entries here, never
 * inline a new lucide-react import elsewhere — keeping it centralized makes
 * icon swaps a single-file edit. The map preserves tree-shaking because every
 * referenced component is imported statically above.
 */
const MAP = {
  account_balance_wallet: Wallet,
  add: Plus,
  arrow_downward: ArrowDown,
  arrow_drop_down: ChevronDown,
  arrow_drop_up: ChevronUp,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  auto_awesome: Sparkles,
  bar_chart: BarChart3,
  bolt: Zap,
  bot: Bot,
  calendar_today: CalendarDays,
  call_split: Split,
  category: LayoutGrid,
  check: Check,
  check_box: CheckSquare,
  check_box_outline_blank: Square,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Copy,
  content_paste: ClipboardPaste,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  delete: Trash2,
  delete_forever: Trash2,
  description: FileText,
  donut_large: PieChart,
  download: Download,
  drag_indicator: GripVertical,
  edit: Pencil,
  email: Mail,
  error: AlertCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  filter_alt: Filter,
  folder: Folder,
  group: Users,
  help_outline: MessageCircleQuestion,
  info: Info,
  insert_drive_file: File,
  keyboard: Keyboard,
  light_mode: Sun,
  lightbulb: Lightbulb,
  lock: Lock,
  logout: LogOut,
  menu: Menu,
  no_accounts: UserX,
  more_horiz: MoreHorizontal,
  more_vert: MoreVertical,
  person: User,
  person_add: UserPlus,
  person_search: UserSearch,
  picture_as_pdf: FileText,
  progress_activity: Loader2,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  receipt: Receipt,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  remove: Minus,
  remove_circle: X,
  restart_alt: RotateCcw,
  rule: ListChecks,
  savings: PiggyBank,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  table_chart: FileSpreadsheet,
  tag: Tag,
  toggle_off: ToggleLeft,
  toggle_on: ToggleRight,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  undo: Undo2,
  unfold_more: ChevronsUpDown,
  upload: Upload,
  upload_file: FileUp,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: AlertTriangle,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof MAP

interface IconProps {
  name: IconName
  size?: number
  strokeWidth?: number
  className?: string
  style?: React.CSSProperties
  /** Pass `true` to spin (used for loaders) */
  spin?: boolean
  'aria-hidden'?: boolean | 'true' | 'false'
  'aria-label'?: string
}

export function Icon({
  name,
  size = 16,
  strokeWidth = 1.6,
  className,
  style,
  spin = false,
  ...rest
}: IconProps) {
  const Comp = MAP[name]
  const cls = [spin ? 'animate-spin' : '', className].filter(Boolean).join(' ') || undefined
  return <Comp size={size} strokeWidth={strokeWidth} className={cls} style={style} {...rest} />
}
